### ISSUE TITLE
Form Field Not Clearing on Submit

### ISSUE THREAD

**Issue by zindlerb** [witheve/Eve#225]
Steps to recreate:

 - Create a new data card with two entries. 
 - Fill out both entries, and click submit

the second fields text has not been cleared. If you click somewhere else before clicking submit this does not happen.

![wiedicpnk5](https://cloud.githubusercontent.com/assets/3388704/9353064/76c98af2-461a-11e5-920b-704d9a430584.gif)

**Comment by joshuafcole** [comment]
Hmm, I'm not able to reproduce this. Can you please post your platform, browser, and browser version? Additionally, please open the dev console and type `DEBUG.SEND = 3` and then repeat the bug, pasting the results?

**Comment by ibdknox** [comment]
This is likely an event ordering issue. What browser are you using?

@joshuafcole I corrected for this in the case of enter (https://github.com/witheve/Eve/blob/master/ui/src/editor.ts#L3647), I'm not sure how it could happen for a button click though. As it should be guaranteed that the blur of the form field comes before the click of the submit. I guess if you did it *just* right you could somehow blur and have the button click register within the same framepaint, which means microReact never saw a version of the element with content and thus thinks it's already clear.

**Comment by zindlerb** [comment]
Sorry I was swamped with work and didn't get the chance to come back to this. I am using Chrome Version 43.0.2357.132 (64-bit) on a Mac running Yosemite. I pulled down the latest master and still see the issue.

![image](https://cloud.githubusercontent.com/assets/3388704/9463884/a4521a5c-4ad4-11e5-8a84-bb95b0343bd7.png)

It only happens when I don't unfocus the second input before submitting.
