### ISSUE TITLE
TypeScript compiler is missing after fresh install

### ISSUE THREAD

**Issue by gabriel-fallen** [witheve/Eve#342]
I've just cloned the repository and followed install instructions:
```
npm install
npm run dev
```

I'm getting error `Can't find 'bin/src/server.js'`

`server.ts` doesn't get compiled due to absence of tsd compiler at assumed path:
```
if(program.server) {
  exec("node_modules/tsify/node_modules/typescript/bin/tsc", ["-m", "commonjs"], function(out,err) {
```

I have "node_modules/tsify" directory but there is no "node_modules" directory inside.

I suspect `npm install` wasn't enough to complete the installation.

As long as I have `tsd` compiler in my `PATH` I've changed the line that compiles server like that:
```
exec("tsc", ["-m", "commonjs"], function(out,err) {
```
and now server starts successfully.

I hope this will help. :)

**Comment by lovelyKensho** [comment]
I found the same issue. Your fix worked.

**Comment by joshuafcole** [comment]
This has been fixed on master. https://github.com/witheve/Eve/blob/master/run.js#L299

We still want to use our internal tsc version to prevent weird environment configuration errors for people building Eve. It should be installed by `npm i` via tsify. There was likely a transient issue during your npm install (or using windows, which appears in some cases to refuse to run node scripts without explicitly calling the node executable first) which was elided due to the run script not checking for errors when building and launching the server. Please try pulling latest, re-running `npm i` in the root project directory, and then running `npm run dev` again. If that doesn't work for you, please let me know and I'll re-open the issue.

**Comment by joshuafcole** [comment]
This might also be caused by using npm3 instead of npm2. Can you please let us know what npm version you're using? We currently only support npm2.

**Comment by gabriel-fallen** [comment]
Yep, the issue is still there for me and yep I'm (apparently) using npm3 (3.3.12).
By the way during `npm install` I get this warning:
```
npm WARN install Couldn't install optional dependency: Unsupported
```

I agree that it's very handy wen you carry tsc compiler with Eve and don't have extra requirements apart from node and npm. But I think it makes sense to have a config option for choosing which tsc compiler to use (bundled or external one) for people that have tsc installed anyway.

By the way is that line the only place where tsc gets called? Or do I need to change something else to make Eve properly work on my machine?

Thanks for the effort!

**Comment by joshuafcole** [comment]
The core issue is that tsify will use it's internal tsc version regardless,
which means the server and client code will be compiled with different
typescript versions in that scenario. The server is currently pretty
sparse, so that might be incidentally fine, but since TS is a young
language and new major versions have been breaking in the past, that's a
pretty risky game to play. Moving off of browserify is on the roadmap, but
won't begin until after the next release. I've been avoiding the upgrade
due to its breaking nature and the fact that it doesn't support downgrading
to npm2. I think the real solution is to make a sacrificial VM to install
npm3 on and figure out how to provide version detection for the run script,
so it knows what path to grab tsc at. Please make an issue and I'll try to
make sure this is buttoned up by the end of next week. Alternatively, if
you or anyone else is sufficiently motivated, we'd welcome a PR which has
the version detection built in to select the appropriate tsc path.

Thanks for bringing this to our attention.

**Comment by gabriel-fallen** [comment]
Apparently I have `tsc` inside Eve installation via this path:
```
node_modules/typescript/bin/tsc
```
And symlinc to it in
```
node_modules/.bin/
```

Maybe that's enough to detect npm3 installation?
How can I check that `tsify` isn't broken and really uses this `tsc`?
After that I guess I can make a patch...

**Comment by kristianmandrup** [comment]
I had a similar problem, using npm `3.3.12` and node `v5.5.0`

```
npm run dev
Cannot find module Eve/node_modules/tsify/node_modules/typescript/bin/tsc
```

In node 3.x it flattens out the dependencies, so you avoid deeply nested `node_modules` folders. Looks like Eve still expects the npm 2.x dependency structure? 

I'd like to help with a fix if I can...
